import * as Blockly from 'blockly/core';
import { javascriptGenerator } from 'blockly/javascript';
Blockly.Blocks['jg_api_express_main'] = {
  init: function () {
    this.jsonInit({
      message0: 'Create express site on port %3 then %1 %2',
      colour: '#4abc79',
      args0: [
        {
          type: 'input_dummy'
        },
        {
          type: 'input_statement',
          name: 'STATEMENTS'
        },
        {
          type: 'input_value',
          name: 'PORT',
          check: 'Number'
        }
      ],
      tooltip: 'Start a webserver on a certain port.'
    });
  }
};

javascriptGenerator.forBlock['jg_api_express_main'] = (block) => {
  const statements = javascriptGenerator.statementToCode(block, 'STATEMENTS');
  const port = javascriptGenerator.valueToCode(block, 'PORT', javascriptGenerator.ORDER_ATOMIC);
  const code = `let S4D_APP_EXPRESS = require('express')
let S4D_APP_EXPRESS_bodyParser = require('body-parser');
let S4D_APP_EXPRESS_cors = require('cors');
let S4D_APP_EXPRESS_path = require('path');
let S4D_APP_EXPRESS_app = S4D_APP_EXPRESS();
let S4D_APP_EXPRESS_port = ${port};

S4D_APP_EXPRESS_app.use(S4D_APP_EXPRESS_cors());
S4D_APP_EXPRESS_app.use(S4D_APP_EXPRESS_bodyParser.urlencoded({
    extended: false
}));
S4D_APP_EXPRESS_app.use(S4D_APP_EXPRESS_bodyParser.json());
  
${statements}

// Generated by Scratch For Discord
// Blocks made on Scratch For Anything
S4D_APP_EXPRESS_app.listen(S4D_APP_EXPRESS_port, () => console.log('Listening on port ' + S4D_APP_EXPRESS_port));`;
  return code;
};
